apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdockermvcapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdockermvcapp
  template:
    metadata:
      labels:
        app: testdockermvcapp
    spec:
      containers:
      - name: testdockermvcapp
        image: merosansar/testdockermvcapp:__IMAGE_TAG__  # <-- Will be replaced in workflow
        imagePullPolicy: Always   # <--- Add this line here
        ports:
        - containerPort: 8080  # Change this if your app listens on a different port