apiVersion: v1
kind: Service
metadata:
  name: testdockermvcapp-service
spec:
  type: NodePort
  selector:
    app: testdockermvcapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080  # You can access your app at 
    protocol: TCP
